TARGET = XP-DSC-BLDC
APP_NAME = 
XCC_FLAGS = -g -O2
USED_MODULES = module_mii_singlethread

# Use the latest 1v* version of module_xmos_common
-include ../module_xcommon/build/Makefile.common
-include ../../xcommon/module_xcommon/build/Makefile.common
