TARGET = XK-1
APP_NAME = 
XCC_FLAGS = -g -O2
USED_MODULES = module_ethernet_smi


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
