TARGET = XK-1500
APP_NAME = 
XCC_FLAGS = -g -O2 -report
USED_MODULES = module_mii_singlethread

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
