SPHINX_PROJECT_NAME=Ethernet Component
VERSION=1v4
DOXYGEN_DIRS=../../sc_ethernet/module_ethernet ../../sc_ethernet/module_mii_singlethread
SOURCE_INCLUDE_DIRS=../../sc_ethernet
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
