SPHINX_PROJECT_NAME=Ethernet Component
VERSION=1v4
DOXYGEN_DIRS=../../module_ethernet ../../module_ethernet_smi
SOURCE_INCLUDE_DIRS=../../../sc_ethernet
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
